"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Areas, Criteria, Plans } from "./modules-admin";
import { Audit, Issues, Reports } from "./modules-workflow";
type Screen="dashboard"|"areas"|"criteria"|"plans"|"audit"|"issues"|"reports";
type Status="Uygun"|"Kısmi"|"Uygunsuz"|"Bekliyor";
type Row={id:number;category:string;item:string;weight:number;status:Status;note:string;photos:string[]};
const menu:[Screen,string,string][]=[["dashboard","Genel Bakış","⌂"],["areas","Alan & QR Yönetimi","▦"],["criteria","Kriter Yönetimi","☷"],["plans","Tetkik Planlama","◷"],["audit","Mobil Tetkik","✓"],["issues","Uygunsuzluklar","!"],["reports","Raporlar","▥"]];
const seedRows:Row[]=[
 {id:1,category:"Ayıklama",item:"Gereksiz malzeme ve ekipman çalışma alanından uzaklaştırılmıştır.",weight:15,status:"Uygun",note:"",photos:[]},
 {id:2,category:"Düzenleme",item:"Malzemelerin tanımlı yerleri ve görsel işaretlemeleri mevcuttur.",weight:15,status:"Kısmi",note:"Yedek merdane alanında zemin işaretleri silinmiş.",photos:[]},
 {id:3,category:"Temizlik",item:"Zemin, makine ve ekipmanlar temiz durumdadır.",weight:20,status:"Uygun",note:"",photos:[]},
 {id:4,category:"Standartlaştırma",item:"5S standartları ve kontrol listeleri günceldir.",weight:20,status:"Uygunsuz",note:"Panoda kriter tablosunun eski sürümü bulunuyor.",photos:[]},
 {id:5,category:"Disiplin",item:"Tanımlı 5S kuralları çalışanlar tarafından uygulanmaktadır.",weight:20,status:"Uygun",note:"",photos:[]},
 {id:6,category:"İSG",item:"Yürüyüş yolları ve acil çıkışlar açık durumdadır.",weight:10,status:"Bekliyor",note:"",photos:[]},
];
const factor:Record<Status,number>={Uygun:1,Kısmi:.5,Uygunsuz:0,Bekliyor:0};
const areas=[{no:"A-01",name:"Sıcak Haddehane",sub:"Merdane Hazırlama",owner:"Ahmet Demir",status:"Aktif"},{no:"A-02",name:"Çelikhane",sub:"Konverter Bölgesi",owner:"Selin Arslan",status:"Aktif"},{no:"A-03",name:"Soğuk Haddehane",sub:"Paketleme",owner:"Murat Şahin",status:"Aktif"},{no:"A-04",name:"Merkez Laboratuvar",sub:"Numune Hazırlama",owner:"Ece Kaya",status:"Pasif"}];
function Logo(){return <div className="logo"><img src="https://argemip.org/storage/media/569/conversions/1200px-erdemir-logosvg-crop.png" alt="Erdemir"/><span>Dijital 5S Tetkik Sistemi</span></div>}
function Qr({cells}:{cells:boolean[]}){return <div className="qr">{cells.map((on,i)=><i key={i} className={on?"on":""}/>)}</div>}

export default function Home(){
 const[logged,setLogged]=useState(false),[role,setRole]=useState("Yönetici"),[screen,setScreen]=useState<Screen>("dashboard"),[rows,setRows]=useState(seedRows),[active,setActive]=useState<number|null>(null),[qr,setQr]=useState(false),[qrName,setQrName]=useState("Sıcak Haddehane"),[search,setSearch]=useState(""),[notice,setNotice]=useState(3),[planPublished,setPlanPublished]=useState(false),[issueState,setIssueState]=useState("Düzeltme Bekliyor"),[saveState,setSaveState]=useState("Kaydet");
 const file=useRef<HTMLInputElement>(null),score=Math.round(rows.reduce((a,r)=>a+r.weight*factor[r.status],0)),done=rows.filter(r=>r.status!=="Bekliyor").length,selected=rows.find(r=>r.id===active);
 const update=(id:number,p:Partial<Row>)=>setRows(rs=>rs.map(r=>r.id===id?{...r,...p}:r));
 const addPhotos=async(f:FileList|null)=>{if(!f||active===null)return;const urls:string[]=[];for(const photo of Array.from(f)){const form=new FormData();form.set("file",photo);form.set("criterionId",String(active));const response=await fetch("/api/evidence",{method:"POST",body:form});if(response.ok)urls.push((await response.json()).url)}update(active,{photos:[...(selected?.photos||[]),...urls]})};
 const persist=async()=>{setSaveState("Kaydediliyor...");const response=await fetch("/api/audits/current",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows,score,issueState,planPublished})});setSaveState(response.ok?"✓ Kaydedildi":"Kayıt başarısız");setTimeout(()=>setSaveState("Kaydet"),2200)};
 useEffect(()=>{if(!logged)return;fetch("/api/audits/current").then(r=>r.ok?r.json():null).then(data=>{const saved=data?.audit?.payload;if(saved?.rows)setRows(saved.rows);if(saved?.issueState)setIssueState(saved.issueState);if(typeof saved?.planPublished==="boolean")setPlanPublished(saved.planPublished)}).catch(()=>undefined)},[logged]);
 const cells=useMemo(()=>Array.from({length:441},(_,i)=>{const x=i%21,y=Math.floor(i/21),finder=(a:number,b:number)=>x>=a&&x<a+7&&y>=b&&y<b+7&&(x===a||x===a+6||y===b||y===b+6||(x>=a+2&&x<=a+4&&y>=b+2&&y<=b+4));return finder(0,0)||finder(14,0)||finder(0,14)||((i*13+x*y+142)%7<3)}),[]);
 if(!logged)return <Login role={role} setRole={setRole} enter={()=>{setLogged(true);setScreen(role==="Tetkikçi"?"audit":role==="Alan Sorumlusu"?"issues":"dashboard")}}/>;
 const allowed=role==="Yönetici"?menu:menu.filter(([id])=>(role==="Tetkikçi"?["dashboard","audit","reports"]:["dashboard","issues","reports"]).includes(id));
 return <main className="system-shell"><Sidebar allowed={allowed} screen={screen} role={role} go={setScreen} logout={()=>setLogged(false)}/><section className="content"><header className="system-top"><span>{menu.find(m=>m[0]===screen)?.[1]}</span><div><button className="db-save" onClick={persist}>{saveState}</button><button className="bell" onClick={()=>setNotice(0)}>♢{notice>0&&<b>{notice}</b>}</button><button className="help">Yardım</button></div></header><div className="module">{screen==="dashboard"&&<Dashboard go={setScreen}/>} {screen==="areas"&&<Areas openQr={n=>{setQrName(n);setQr(true)}}/>} {screen==="criteria"&&<Criteria/>} {screen==="plans"&&<Plans published={planPublished} setPublished={setPlanPublished}/>} {screen==="audit"&&<Audit rows={rows} score={score} done={done} search={search} setSearch={setSearch} update={update} openEvidence={setActive} openQr={()=>{setQrName("Sıcak Haddehane / Merdane Hazırlama");setQr(true)}} save={persist} saveState={saveState}/>} {screen==="issues"&&<Issues state={issueState} setState={setIssueState}/>} {screen==="reports"&&<Reports/>}</div></section>
 <Evidence selected={selected} file={file} update={update} addPhotos={addPhotos} close={()=>setActive(null)}/>{qr&&<QrModal name={qrName} cells={cells} close={()=>setQr(false)}/>}</main>
}
function PageTitle({tag,title,text,action}:{tag:string,title:string,text:string,action?:React.ReactNode}){return <div className="module-title"><div><span className="eyebrow">{tag}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Login({role,setRole,enter}:{role:string,setRole:(s:string)=>void,enter:()=>void}){return <main className="login"><section className="login-visual"><div className="steel-lines"/><div className="login-copy"><span>ERDEMİR · DİJİTAL OPERASYON</span><h1>5S’i sahada yönet,<br/>sonucu anında gör.</h1><p>Planlamadan düzeltici faaliyet onayına kadar tüm 5S tetkik süreci tek merkezde.</p></div></section><section className="login-panel"><Logo/><div className="login-box"><span className="eyebrow">GÜVENLİ KURUMSAL ERİŞİM</span><h2>Tekrar hoş geldiniz</h2><p>Yetkinize göre çalışma alanınıza yönlendirileceksiniz.</p><label>Kullanıcı adı<input defaultValue="pelin.yener"/></label><label>Şifre<input type="password" defaultValue="12345678"/></label><label>Demo rolü<select value={role} onChange={e=>setRole(e.target.value)}><option>Yönetici</option><option>Tetkikçi</option><option>Alan Sorumlusu</option></select></label><div className="login-meta"><label><input type="checkbox" defaultChecked/> Beni hatırla</label><button>Şifremi unuttum</button></div><button className="primary wide" onClick={enter}>Giriş yap <b>→</b></button><small className="secure">▣ Güvenli kurumsal bağlantı</small></div></section></main>}
function Sidebar({allowed,screen,role,go,logout}:{allowed:[Screen,string,string][],screen:Screen,role:string,go:(s:Screen)=>void,logout:()=>void}){return <aside className="sidebar"><Logo/><div className="role"><span>PY</span><div><b>Pelin Yener</b><small>{role}</small></div></div><nav>{allowed.map(([id,label,icon])=><button key={id} className={screen===id?"active":""} onClick={()=>go(id)}><i>{icon}</i>{label}{id==="issues"&&<em>2</em>}</button>)}</nav><div className="side-bottom"><button onClick={logout}>↪ Çıkış yap</button><small>5S Sistem · v1.0</small></div></aside>}
function Evidence({selected,file,update,addPhotos,close}:{selected:Row|undefined,file:React.RefObject<HTMLInputElement|null>,update:(id:number,p:Partial<Row>)=>void,addPhotos:(f:FileList|null)=>void,close:()=>void}){if(!selected)return null;return <div className="overlay" onMouseDown={close}><aside onMouseDown={e=>e.stopPropagation()}><div className="side-head"><div><span className="eyebrow">KRİTER {String(selected.id).padStart(2,"0")}</span><h2>Uygunsuzluk ve kanıt</h2></div><button onClick={close}>×</button></div><p className="criterion">{selected.item}</p><label className="field">Değerlendirme<select value={selected.status} onChange={e=>update(selected.id,{status:e.target.value as Status})}><option>Uygun</option><option>Kısmi</option><option>Uygunsuz</option><option>Bekliyor</option></select></label><label className="field">Uygunsuzluk açıklaması<textarea value={selected.note} onChange={e=>update(selected.id,{note:e.target.value})}/></label><label className="field">Zorunlu fotoğraf kanıtı<button className="camera" onClick={()=>file.current?.click()}><b>📷</b><strong>Fotoğraf çek veya yükle</strong><small>Mobil kamera desteklenir · JPG, PNG</small></button><input ref={file} hidden type="file" accept="image/*" capture="environment" multiple onChange={e=>addPhotos(e.target.files)}/></label><div className="side-actions"><button className="outline" onClick={close}>Vazgeç</button><button className="primary" disabled={selected.status==="Uygunsuz"&&selected.photos.length===0} onClick={close}>Kanıtı kaydet</button></div></aside></div>}
function QrModal({name,cells,close}:{name:string,cells:boolean[],close:()=>void}){return <div className="overlay modal-wrap" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button><span className="eyebrow">BENZERSİZ ALAN QR KODU</span><h2>{name}</h2><p>Okutulduğunda alanın aktif kriter tablosu açılır.</p><Qr cells={cells}/><b>ERD-5S-A01-2026</b><div className="modal-actions"><button className="outline" onClick={()=>window.print()}>Yazdır</button><button className="primary" onClick={()=>alert("QR kodu cihaza indirildi.")}>Cihaza indir</button></div></div></div>}
function Dashboard({go}:{go:(s:Screen)=>void}){return <><PageTitle tag="19 AĞUSTOS 2026 · ÇARŞAMBA" title="5S Yönetim Merkezi" text="Tüm alanların güncel durumu ve bekleyen işlemler." action={<button className="primary" onClick={()=>go("plans")}>＋ Yeni tetkik planı</button>}/><div className="kpis"><article><small>GENEL 5S PUANI</small><b>86,4</b><em className="up">↑ 3,2 puan</em></article><article><small>AKTİF TETKİK</small><b>12</b><em>4’ü bugün</em></article><article><small>AÇIK UYGUNSUZLUK</small><b>7</b><em className="danger-text">2 gecikmiş</em></article><article><small>ONAY BEKLEYEN</small><b>3</b><em>Düzeltici faaliyet</em></article></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h3>Alan performansı</h3><p>Son tamamlanan tetkik puanları</p></div><button onClick={()=>go("reports")}>Tüm raporlar →</button></div>{[["Sıcak Haddehane",91],["Çelikhane",84],["Soğuk Haddehane",78],["Merkez Laboratuvar",94]].map(([n,v])=><div className="bar-row" key={String(n)}><span>{n}</span><div><i style={{width:`${v}%`}}/></div><b>{v}</b></div>)}</section><section className="panel activity"><div className="panel-head"><div><h3>Bekleyen işlemler</h3><p>Öncelik sırasına göre</p></div></div><button onClick={()=>go("issues")}><i className="urgent">!</i><span><b>2 uygunsuzluk gecikti</b><small>Sıcak Haddehane</small></span><em>İncele →</em></button><button onClick={()=>go("plans")}><i>◷</i><span><b>Ağustos planı yayımlanacak</b><small>8 tetkikçi atanmayı bekliyor</small></span><em>Planla →</em></button><button onClick={()=>go("criteria")}><i>☷</i><span><b>Kriter v3.2 taslakta</b><small>5 değişiklik onay bekliyor</small></span><em>Aç →</em></button></section></div></>}
